export const colores = {
    // primary: "#84b6f4",
    // red: "#f7cae7",
    // // success: "#95fab9",
    // primary: "",
    // red: "#F8485E",
    // success: "#512D6D",
    primary: "black",
    light: 'white',
    secundary: "#ffb703",
    success: "#fb8500",
    tertiary: "#8ecae6",
    extra: '#00C1D4',
    background: "#0a0a0a",
    black_text: "#0a0a0a",
    white_text: "#ffffff",
};